apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Project.Deployment.Name}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: #{Project.Labels.Component}
  template:
    metadata:
      labels:
        component: #{Project.Labels.Component}
    spec:
      containers:
        - name: web
          image: octopussamples/octopub-frontend:#{Project.Container.Tag}
          ports:
            - containerPort: 8080
              name: http-port